package com.spectra.ar.ar

enum class ArAvailability { SUPPORTED_READY, SUPPORTED_NEEDS_INSTALL, SUPPORTED_NEEDS_UPDATE, UNSUPPORTED, UNKNOWN }

enum class TrackingState { TRACKING, PAUSED_INITIALIZING, PAUSED_INSUFFICIENT_FEATURES, PAUSED_EXCESSIVE_MOTION, STOPPED }
